#!/bin/sh
WIN32_RUNTIME_PATH=`pwd`/xulrunner_win32
LINUX_RUNTIME_PATH=`pwd`/xulrunner_linux-i686

RAN=`uuidgen | head -c 8`  # Get random 8-character string for build directory
CALLDIR=`pwd`
BUILDDIR=/tmp/zotero-build-$RAN
SVNPREFIX="https://www.zotero.org/svn/extension/"
SVNPATH="$1" # e.g. branches/1.0, defaults to "trunk"
REV="$2" # Revision normally supplied by SVN post-commit script (to speed things up) or left blank

mkdir $BUILDDIR

if [ -z $SVNPATH ]; then SVNPATH="trunk"; fi
URL=${SVNPREFIX}${SVNPATH}/

# If revision not supplied, checkout and use svnversion to get latest revision
if [ -z $REV ]; then
	svn co --quiet --username zotero --password kn0wl3dge --non-interactive $URL $BUILDDIR/zotero
	cd $BUILDDIR/zotero
	REV=`svnversion .`
	cd ..
	rm -rf $BUILDDIR/zotero
fi

# Export a clean copy of the tree
svn export --quiet --username zotero --password kn0wl3dge --non-interactive $URL $BUILDDIR/zotero
echo

# Zip chrome into JAR and adjust chrome.manifest
cd $BUILDDIR/zotero/chrome
# Checkout failed -- bail
if [ $? -eq 1 ]; then
	exit;
fi

zip -0 -r ../zotero.jar .
rm -rf $BUILDDIR/zotero/chrome/*
mv ../zotero.jar .
cd ..

# Build translators.zip
if [ -d translators ]; then
	cd translators
	mkdir output
	counter=0;
	for file in *.js; do
		newfile=$counter.js;
		cp "$file" output/$newfile;
		counter=$(($counter+1))
	done;
	cd output
	zip ../../translators.zip *
	cd ../..
	rm -rf translators
fi

# Build styles.zip with default styles
if [ -d styles ]; then
	cd styles
	for i in *.csl; do
		svn export https://www.zotero.org/svn/csl/$i;
	done
	zip ../styles.zip *
	cd ..
	rm -rf styles
fi

# Mac
echo 'Building Zotero.app'
APPDIR=$CALLDIR/Zotero.app
mkdir $APPDIR
chmod 755 $APPDIR
cp -r $CALLDIR/Contents $APPDIR
CONTENTSDIR=$APPDIR/Contents

mkdir $CONTENTSDIR/MacOS
mkdir $CONTENTSDIR/Frameworks
ditto /Library/Frameworks/XUL.framework $CONTENTSDIR/Frameworks/XUL.framework
ln -s ../Frameworks/XUL.framework/Versions/Current/xulrunner $CONTENTSDIR/MacOS/zotero
cp $CALLDIR/application.ini $CONTENTSDIR/Resources

cp -r $BUILDDIR/zotero/* $CONTENTSDIR/Resources
cp $CALLDIR/prefs.js $CONTENTSDIR/Resources/defaults/preferences
cp $CALLDIR/chrome.manifest $CONTENTSDIR/Resources/chrome/chrome.manifest

# Win32
echo 'Building Zotero_Win32'
APPDIR=$CALLDIR/Zotero_Win32
mkdir $APPDIR

cp -r $BUILDDIR/zotero/* $CALLDIR/application.ini $APPDIR
cp -r $WIN32_RUNTIME_PATH $APPDIR/xulrunner
cp $CALLDIR/prefs.js $APPDIR/defaults/preferences
cp $CALLDIR/chrome.manifest $APPDIR/chrome/chrome.manifest
mv $APPDIR/xulrunner/xulrunner-stub.exe $APPDIR/zotero.exe

# Linux
echo 'Building Zotero_Linux-i686'
APPDIR=$CALLDIR/Zotero_Linux-i686
mkdir $APPDIR

cp -r $BUILDDIR/zotero/* $CALLDIR/application.ini $APPDIR
cp -r $LINUX_RUNTIME_PATH $APPDIR/xulrunner
cp $CALLDIR/prefs.js $APPDIR/defaults/preferences
cp $CALLDIR/chrome.manifest $APPDIR/chrome/chrome.manifest
mv $APPDIR/xulrunner/xulrunner-stub $APPDIR/zotero
chmod 755 $APPDIR/zotero

rm -rf $BUILDDIR