#!/bin/bash
SITE=https://ftp.mozilla.org/pub/mozilla.org/xulrunner/nightly/latest-trunk/
VERSION=2.0b12pre

rm -rf xulrunner
mkdir xulrunner
cd xulrunner

curl -O $SITE/xulrunner-$VERSION.en-US.mac64-pkg.dmg \
	-O $SITE/xulrunner-$VERSION.en-US.win32.zip \
	-O $SITE/xulrunner-$VERSION.en-US.linux-i686.tar.bz2 \
	-O $SITE/xulrunner-$VERSION.en-US.linux-x86_64.tar.bz2 

hdiutil detach -quiet /Volumes/XULRunner 2>/dev/null
hdiutil attach -quiet xulrunner-$VERSION.en-US.mac64-pkg.dmg
gunzip -c /Volumes/XULRunner/xulrunner-$VERSION.en-US.mac64.pkg/Contents/Archive.pax.gz | pax -r
hdiutil detach -quiet /Volumes/XULRunner
rm xulrunner-$VERSION.en-US.mac64-pkg.dmg

unzip -q xulrunner-$VERSION.en-US.win32.zip
rm xulrunner-$VERSION.en-US.win32.zip
mv xulrunner xulrunner_win32

tar -xjf xulrunner-$VERSION.en-US.linux-i686.tar.bz2
rm xulrunner-$VERSION.en-US.linux-i686.tar.bz2
mv xulrunner xulrunner_linux-i686

tar -xjf xulrunner-$VERSION.en-US.linux-x86_64.tar.bz2
rm xulrunner-$VERSION.en-US.linux-x86_64.tar.bz2
mv xulrunner xulrunner_linux-x86_64