#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/config.sh"

function usage {
	cat >&2 <<DONE
Usage: $0 [-s PATH] VERSION
Options
 -s S3_PATH           Path within S3 standalone directory (e.g., 'beta' for /standalone/beta)
DONE
	exit 1
}

S3_PATH=""
while getopts "s:" opt; do
	case $opt in
		s)
			S3_PATH="$OPTARG"
			;;
		*)
			usage
			;;
	esac
	shift $((OPTIND-1)); OPTIND=1
done

shift $(($OPTIND - 1))
VERSION="$1"

if [ -z "$VERSION" ]; then
	usage
fi

DIST_DIR="$DIR/dist/"
S3_PATH="$S3_BUCKET/standalone/$S3_PATH/$VERSION/"

aws s3 cp --recursive --exclude files --exclude sha512sums "$DIST_DIR" s3://${S3_PATH}
