#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$ROOT_DIR"

if [ "`uname`" = "Darwin" ]; then
	PLATFORM="m"
elif [ "`uname`" = "Linux" ]; then
	PLATFORM="l"
elif [ "`uname -o 2> /dev/null`" = "Cygwin" ]; then
	PLATFORM="w"
fi

CHANNEL="source"

VERSION=`perl -ne 'print and last if s/.*<em:version>(.{3}).+/\1/;' "$ROOT_DIR/../zotero/install.rdf"`
if [ $VERSION = "4.0" ]; then
	"$ROOT_DIR/../zotero-build/xpi/build_xpi_4.0" "$ROOT_DIR/../zotero" $CHANNEL
else
	"$ROOT_DIR/../zotero-build/xpi/build_xpi" -s "$ROOT_DIR/../zotero" -c $CHANNEL
fi

"$ROOT_DIR/build.sh" -f "$ROOT_DIR/../zotero-build/xpi/build/zotero-build.xpi" -p $PLATFORM -d -c $CHANNEL
